- apiVersion: v1
  kind: Service
  metadata:
    labels:
      io.qa.service: flowable
    #annotations:
        #service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        # service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
    name: flowable
    namespace: fda-qa
  spec:
    ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
    selector:
      io.qa.service: flowable
    type: NodePort


- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      io.qa.service: ief-tensorflow
    name: ief-tensorflow
    namespace: fda-qa
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.qa.service: ief-tensorflow
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.qa.service: ief-tensorflow
      spec:
        containers:
        - image: 564105391044.dkr.ecr.us-east-1.amazonaws.com/ief-tensorflow-qa:latest
          name: ief-tensorflow
          imagePullPolicy: "Always"
          ports:
          - containerPort: 8801
          resources:
            requests:
              memory: "16Gi"
          volumeMounts:
          - name: persistent-storage1
            mountPath: /modelstore
        volumes:
        - name: persistent-storage1
          persistentVolumeClaim:
            claimName: efs-ief-common-pvc
        imagePullSecrets:
        - name: docker-dailyupdatecredentials
        restartPolicy: Always
  status: {}
