- apiVersion: v1
  kind: Service
  metadata:
    labels:
      io.qa.service: flowable
    #annotations:
        #service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        # service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "300"
    name: flowable
    namespace: fda-qa
  spec:
    ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
    selector:
      io.qa.service: flowable
    type: NodePort


- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      io.qa.service: flowable
    name: flowable
    namespace: fda-qa
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.qa.service: flowable
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.qa.service: flowable
      spec:
        containers:
        - image: 564105391044.dkr.ecr.us-east-1.amazonaws.com/flowable-qa:4.0
          name: flowable
          imagePullPolicy: "Always"
          ports:
          - containerPort: 8086
          resources:
            requests:
              memory: "2Gi"
          volumeMounts:
          - name: persistent-flowable
            mountPath: /home/ubuntu/FDA/Logs/orchestration/
        volumes:
        - name: persistent-flowable
          persistentVolumeClaim:
            claimName: efs-flowable-qa-1
        imagePullSecrets:
        - name: docker-dailyupdatecredentials
        restartPolicy: Always
  status: {}
